### ISSUE TITLE
Use endpoint for summary field

### ISSUE THREAD

**Issue by thekaveman** [openmobilityfoundation/mds-openapi#23]
E.g. in the [Provider API](https://github.com/openmobilityfoundation/mds-openapi/blob/main/reference/provider.yaml#L45) doc we have:

```yaml
/vehicles:
    get:
      operationId: get-vehicles
      description: Get a list of known vehicles, with properties that do not change often.
      summary: Get near-realtime vehicle information.
```

In the Stoplight menu, this looks like _(notice some items are cut off)_:

<img width="206" alt="image" src="https://user-images.githubusercontent.com/1783439/235558786-4a1c19a1-a44d-469e-a5fc-0228a30a452b.png">

Instead reuse the endpoint name in the `summary` field:

```yaml
/vehicles:
    get:
      operationId: get-vehicles
      description: Get a list of known vehicles, with properties that do not change often.
      summary: /vehicles
```

This will reduce duplication within these OpenAPI docs and with the MDS docs, and it makes it much clearer in the Stoplight menu:

<img width="205" alt="image" src="https://user-images.githubusercontent.com/1783439/235559171-70ab9ba5-661c-45c3-a2a9-7a65561e44d3.png">
